import {
    BadgeIndianRupee,
    CalendarDays,
    ChartNoAxesCombined,
    Check,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    Home,
    Import,
    LogOut,
    Moon,
    Navigation,
    Plus,
    Settings,
    SquarePen,
    Tag,
    Trash2,
    User,
    UsersRound,
    X,
} from 'lucide-react';

export const iconMap = {
    badgeIndianRupee: BadgeIndianRupee,
    calendar: CalendarDays,
    check: Check,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    edit: SquarePen,
    home: Home,
    import: Import,
    logOut: LogOut,
    moon: Moon,
    navigation: Navigation,
    plus: Plus,
    profiles: UsersRound,
    report: ChartNoAxesCombined,
    settings: Settings,
    tag: Tag,
    trash: Trash2,
    user: User,
    x: X,
} as const;

export type IconName = keyof typeof iconMap;
