// This file is auto-generated by packages/ui/scripts/generate-theme-colors.mjs.
// Do not edit it manually.

export type ThemeColorToken = {
    key: string;
    label: string;
    cssVar: string;
    value?: {
        light?: string;
        dark?: string;
    };
};

export const themeColorTokens: Record<string, ThemeColorToken> = {
    "gray-0": {
        "key": "gray-0",
        "label": "Gray 0",
        "cssVar": "--gray-0",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "gray-50": {
        "key": "gray-50",
        "label": "Gray 50",
        "cssVar": "--gray-50",
        "value": {
            "light": "#f9fafb",
            "dark": "#111827"
        }
    },
    "gray-100": {
        "key": "gray-100",
        "label": "Gray 100",
        "cssVar": "--gray-100",
        "value": {
            "light": "#f3f4f6",
            "dark": "#1f2937"
        }
    },
    "gray-200": {
        "key": "gray-200",
        "label": "Gray 200",
        "cssVar": "--gray-200",
        "value": {
            "light": "#e5e7eb",
            "dark": "#273244"
        }
    },
    "gray-300": {
        "key": "gray-300",
        "label": "Gray 300",
        "cssVar": "--gray-300",
        "value": {
            "light": "#d1d5db",
            "dark": "#334155"
        }
    },
    "gray-400": {
        "key": "gray-400",
        "label": "Gray 400",
        "cssVar": "--gray-400",
        "value": {
            "light": "#9ca3af",
            "dark": "#475569"
        }
    },
    "gray-500": {
        "key": "gray-500",
        "label": "Gray 500",
        "cssVar": "--gray-500",
        "value": {
            "light": "#6b7280",
            "dark": "#94a3b8"
        }
    },
    "gray-600": {
        "key": "gray-600",
        "label": "Gray 600",
        "cssVar": "--gray-600",
        "value": {
            "light": "#4b5563",
            "dark": "#cbd5e1"
        }
    },
    "gray-700": {
        "key": "gray-700",
        "label": "Gray 700",
        "cssVar": "--gray-700",
        "value": {
            "light": "#374151",
            "dark": "#e2e8f0"
        }
    },
    "gray-800": {
        "key": "gray-800",
        "label": "Gray 800",
        "cssVar": "--gray-800",
        "value": {
            "light": "#1f2933",
            "dark": "#f1f5f9"
        }
    },
    "gray-900": {
        "key": "gray-900",
        "label": "Gray 900",
        "cssVar": "--gray-900",
        "value": {
            "light": "#111827",
            "dark": "#f8fafc"
        }
    },
    "gray-950": {
        "key": "gray-950",
        "label": "Gray 950",
        "cssVar": "--gray-950",
        "value": {
            "light": "#0b0f19",
            "dark": "#ffffff"
        }
    },
    "blue-50": {
        "key": "blue-50",
        "label": "Blue 50",
        "cssVar": "--blue-50",
        "value": {
            "light": "#eff6ff",
            "dark": "#0b1e3a"
        }
    },
    "blue-100": {
        "key": "blue-100",
        "label": "Blue 100",
        "cssVar": "--blue-100",
        "value": {
            "light": "#dbeafe",
            "dark": "#133a6f"
        }
    },
    "blue-300": {
        "key": "blue-300",
        "label": "Blue 300",
        "cssVar": "--blue-300",
        "value": {
            "light": "#93c5fd",
            "dark": "#60a5fa"
        }
    },
    "blue-500": {
        "key": "blue-500",
        "label": "Blue 500",
        "cssVar": "--blue-500",
        "value": {
            "light": "#2563eb",
            "dark": "#93c5fd"
        }
    },
    "blue-700": {
        "key": "blue-700",
        "label": "Blue 700",
        "cssVar": "--blue-700",
        "value": {
            "light": "#1e40af",
            "dark": "#bfdbfe"
        }
    },
    "purple-50": {
        "key": "purple-50",
        "label": "Purple 50",
        "cssVar": "--purple-50",
        "value": {
            "light": "#f5f3ff",
            "dark": "#1e1033"
        }
    },
    "purple-100": {
        "key": "purple-100",
        "label": "Purple 100",
        "cssVar": "--purple-100",
        "value": {
            "light": "#ede9fe",
            "dark": "#3b1d6a"
        }
    },
    "purple-300": {
        "key": "purple-300",
        "label": "Purple 300",
        "cssVar": "--purple-300",
        "value": {
            "light": "#c4b5fd",
            "dark": "#a78bfa"
        }
    },
    "purple-500": {
        "key": "purple-500",
        "label": "Purple 500",
        "cssVar": "--purple-500",
        "value": {
            "light": "#7c3aed",
            "dark": "#c4b5fd"
        }
    },
    "purple-700": {
        "key": "purple-700",
        "label": "Purple 700",
        "cssVar": "--purple-700",
        "value": {
            "light": "#5b21b6",
            "dark": "#e9d5ff"
        }
    },
    "red-50": {
        "key": "red-50",
        "label": "Red 50",
        "cssVar": "--red-50",
        "value": {
            "light": "#fef2f2",
            "dark": "#2a0c0c"
        }
    },
    "red-100": {
        "key": "red-100",
        "label": "Red 100",
        "cssVar": "--red-100",
        "value": {
            "light": "#fee2e2",
            "dark": "#3f1212"
        }
    },
    "red-300": {
        "key": "red-300",
        "label": "Red 300",
        "cssVar": "--red-300",
        "value": {
            "light": "#fca5a5",
            "dark": "#f87171"
        }
    },
    "red-500": {
        "key": "red-500",
        "label": "Red 500",
        "cssVar": "--red-500",
        "value": {
            "light": "#dc2626",
            "dark": "#fca5a5"
        }
    },
    "red-700": {
        "key": "red-700",
        "label": "Red 700",
        "cssVar": "--red-700",
        "value": {
            "light": "#7f1d1d",
            "dark": "#fecaca"
        }
    },
    "green-50": {
        "key": "green-50",
        "label": "Green 50",
        "cssVar": "--green-50",
        "value": {
            "light": "#ecfdf5",
            "dark": "#022c22"
        }
    },
    "green-100": {
        "key": "green-100",
        "label": "Green 100",
        "cssVar": "--green-100",
        "value": {
            "light": "#d1fae5",
            "dark": "#064e3b"
        }
    },
    "green-300": {
        "key": "green-300",
        "label": "Green 300",
        "cssVar": "--green-300",
        "value": {
            "light": "#6ee7b7",
            "dark": "#34d399"
        }
    },
    "green-500": {
        "key": "green-500",
        "label": "Green 500",
        "cssVar": "--green-500",
        "value": {
            "light": "#16a34a",
            "dark": "#6ee7b7"
        }
    },
    "green-700": {
        "key": "green-700",
        "label": "Green 700",
        "cssVar": "--green-700",
        "value": {
            "light": "#14532d",
            "dark": "#a7f3d0"
        }
    },
    "yellow-50": {
        "key": "yellow-50",
        "label": "Yellow 50",
        "cssVar": "--yellow-50",
        "value": {
            "light": "#fffbeb",
            "dark": "#2e1a00"
        }
    },
    "yellow-100": {
        "key": "yellow-100",
        "label": "Yellow 100",
        "cssVar": "--yellow-100",
        "value": {
            "light": "#fef3c7",
            "dark": "#422006"
        }
    },
    "yellow-300": {
        "key": "yellow-300",
        "label": "Yellow 300",
        "cssVar": "--yellow-300",
        "value": {
            "light": "#fcd34d",
            "dark": "#fbbf24"
        }
    },
    "yellow-500": {
        "key": "yellow-500",
        "label": "Yellow 500",
        "cssVar": "--yellow-500",
        "value": {
            "light": "#d97706",
            "dark": "#fde68a"
        }
    },
    "yellow-700": {
        "key": "yellow-700",
        "label": "Yellow 700",
        "cssVar": "--yellow-700",
        "value": {
            "light": "#92400e",
            "dark": "#fef3c7"
        }
    },
    "orange-50": {
        "key": "orange-50",
        "label": "Orange 50",
        "cssVar": "--orange-50",
        "value": {
            "light": "#fff7ed",
            "dark": "#2a1405"
        }
    },
    "orange-100": {
        "key": "orange-100",
        "label": "Orange 100",
        "cssVar": "--orange-100",
        "value": {
            "light": "#ffedd5",
            "dark": "#3f1d0a"
        }
    },
    "orange-300": {
        "key": "orange-300",
        "label": "Orange 300",
        "cssVar": "--orange-300",
        "value": {
            "light": "#fdba74",
            "dark": "#fb923c"
        }
    },
    "orange-500": {
        "key": "orange-500",
        "label": "Orange 500",
        "cssVar": "--orange-500",
        "value": {
            "light": "#ea580c",
            "dark": "#fdba74"
        }
    },
    "orange-700": {
        "key": "orange-700",
        "label": "Orange 700",
        "cssVar": "--orange-700",
        "value": {
            "light": "#9a3412",
            "dark": "#ffedd5"
        }
    },
    "teal-50": {
        "key": "teal-50",
        "label": "Teal 50",
        "cssVar": "--teal-50",
        "value": {
            "light": "#f0fdfa",
            "dark": "#042f2e"
        }
    },
    "teal-100": {
        "key": "teal-100",
        "label": "Teal 100",
        "cssVar": "--teal-100",
        "value": {
            "light": "#ccfbf1",
            "dark": "#064e4b"
        }
    },
    "teal-300": {
        "key": "teal-300",
        "label": "Teal 300",
        "cssVar": "--teal-300",
        "value": {
            "light": "#5eead4",
            "dark": "#2dd4bf"
        }
    },
    "teal-500": {
        "key": "teal-500",
        "label": "Teal 500",
        "cssVar": "--teal-500",
        "value": {
            "light": "#0d9488",
            "dark": "#5eead4"
        }
    },
    "teal-700": {
        "key": "teal-700",
        "label": "Teal 700",
        "cssVar": "--teal-700",
        "value": {
            "light": "#115e59",
            "dark": "#ccfbf1"
        }
    },
    "cyan-50": {
        "key": "cyan-50",
        "label": "Cyan 50",
        "cssVar": "--cyan-50",
        "value": {
            "light": "#ecfeff",
            "dark": "#042f2e"
        }
    },
    "cyan-100": {
        "key": "cyan-100",
        "label": "Cyan 100",
        "cssVar": "--cyan-100",
        "value": {
            "light": "#cffafe",
            "dark": "#064e4b"
        }
    },
    "cyan-300": {
        "key": "cyan-300",
        "label": "Cyan 300",
        "cssVar": "--cyan-300",
        "value": {
            "light": "#67e8f9",
            "dark": "#22d3ee"
        }
    },
    "cyan-500": {
        "key": "cyan-500",
        "label": "Cyan 500",
        "cssVar": "--cyan-500",
        "value": {
            "light": "#0891b2",
            "dark": "#67e8f9"
        }
    },
    "cyan-700": {
        "key": "cyan-700",
        "label": "Cyan 700",
        "cssVar": "--cyan-700",
        "value": {
            "light": "#164e63",
            "dark": "#cffafe"
        }
    },
    "bg-primary": {
        "key": "bg-primary",
        "label": "Bg Primary",
        "cssVar": "--bg-primary",
        "value": {
            "light": "var(--gray-50)",
            "dark": "var(--gray-0)"
        }
    },
    "bg-secondary": {
        "key": "bg-secondary",
        "label": "Bg Secondary",
        "cssVar": "--bg-secondary",
        "value": {
            "light": "var(--gray-200)",
            "dark": "var(--gray-50)"
        }
    },
    "bg-elevated": {
        "key": "bg-elevated",
        "label": "Bg Elevated",
        "cssVar": "--bg-elevated",
        "value": {
            "light": "var(--gray-0)",
            "dark": "var(--gray-100)"
        }
    },
    "text-primary": {
        "key": "text-primary",
        "label": "Text Primary",
        "cssVar": "--text-primary",
        "value": {
            "light": "var(--gray-800)",
            "dark": "var(--gray-900)"
        }
    },
    "text-secondary": {
        "key": "text-secondary",
        "label": "Text Secondary",
        "cssVar": "--text-secondary",
        "value": {
            "light": "var(--gray-600)",
            "dark": "var(--gray-600)"
        }
    },
    "text-muted": {
        "key": "text-muted",
        "label": "Text Muted",
        "cssVar": "--text-muted",
        "value": {
            "light": "var(--gray-500)",
            "dark": "var(--gray-500)"
        }
    },
    "border-default": {
        "key": "border-default",
        "label": "Border Default",
        "cssVar": "--border-default",
        "value": {
            "light": "var(--gray-200)",
            "dark": "var(--gray-200)"
        }
    },
    "border-subtle": {
        "key": "border-subtle",
        "label": "Border Subtle",
        "cssVar": "--border-subtle",
        "value": {
            "light": "var(--gray-100)",
            "dark": "var(--gray-100)"
        }
    },
    "semantic-success-bg": {
        "key": "semantic-success-bg",
        "label": "Semantic Success Bg",
        "cssVar": "--semantic-success-bg",
        "value": {
            "light": "var(--green-50)",
            "dark": "var(--green-50)"
        }
    },
    "semantic-success-fg": {
        "key": "semantic-success-fg",
        "label": "Semantic Success Fg",
        "cssVar": "--semantic-success-fg",
        "value": {
            "light": "var(--green-700)",
            "dark": "var(--green-700)"
        }
    },
    "semantic-success-border": {
        "key": "semantic-success-border",
        "label": "Semantic Success Border",
        "cssVar": "--semantic-success-border",
        "value": {
            "light": "var(--green-300)",
            "dark": "var(--green-300)"
        }
    },
    "semantic-warning-bg": {
        "key": "semantic-warning-bg",
        "label": "Semantic Warning Bg",
        "cssVar": "--semantic-warning-bg",
        "value": {
            "light": "var(--yellow-50)",
            "dark": "var(--yellow-50)"
        }
    },
    "semantic-warning-fg": {
        "key": "semantic-warning-fg",
        "label": "Semantic Warning Fg",
        "cssVar": "--semantic-warning-fg",
        "value": {
            "light": "var(--yellow-700)",
            "dark": "var(--yellow-700)"
        }
    },
    "semantic-warning-border": {
        "key": "semantic-warning-border",
        "label": "Semantic Warning Border",
        "cssVar": "--semantic-warning-border",
        "value": {
            "light": "var(--yellow-300)",
            "dark": "var(--yellow-300)"
        }
    },
    "semantic-error-bg": {
        "key": "semantic-error-bg",
        "label": "Semantic Error Bg",
        "cssVar": "--semantic-error-bg",
        "value": {
            "light": "var(--red-50)",
            "dark": "var(--red-50)"
        }
    },
    "semantic-error-fg": {
        "key": "semantic-error-fg",
        "label": "Semantic Error Fg",
        "cssVar": "--semantic-error-fg",
        "value": {
            "light": "var(--red-700)",
            "dark": "var(--red-700)"
        }
    },
    "semantic-error-border": {
        "key": "semantic-error-border",
        "label": "Semantic Error Border",
        "cssVar": "--semantic-error-border",
        "value": {
            "light": "var(--red-300)",
            "dark": "var(--red-300)"
        }
    },
    "semantic-info-bg": {
        "key": "semantic-info-bg",
        "label": "Semantic Info Bg",
        "cssVar": "--semantic-info-bg",
        "value": {
            "light": "var(--blue-50)",
            "dark": "var(--blue-50)"
        }
    },
    "semantic-info-fg": {
        "key": "semantic-info-fg",
        "label": "Semantic Info Fg",
        "cssVar": "--semantic-info-fg",
        "value": {
            "light": "var(--blue-700)",
            "dark": "var(--blue-700)"
        }
    },
    "semantic-info-border": {
        "key": "semantic-info-border",
        "label": "Semantic Info Border",
        "cssVar": "--semantic-info-border",
        "value": {
            "light": "var(--blue-300)",
            "dark": "var(--blue-300)"
        }
    },
    "accent-primary": {
        "key": "accent-primary",
        "label": "Accent Primary",
        "cssVar": "--accent-primary",
        "value": {
            "light": "var(--blue-500)",
            "dark": "var(--blue-500)"
        }
    },
    "accent-primary-hover": {
        "key": "accent-primary-hover",
        "label": "Accent Primary Hover",
        "cssVar": "--accent-primary-hover",
        "value": {
            "light": "var(--blue-700)",
            "dark": "var(--blue-700)"
        }
    },
    "accent-secondary": {
        "key": "accent-secondary",
        "label": "Accent Secondary",
        "cssVar": "--accent-secondary",
        "value": {
            "light": "var(--purple-500)",
            "dark": "var(--purple-500)"
        }
    },
    "accent-secondary-hover": {
        "key": "accent-secondary-hover",
        "label": "Accent Secondary Hover",
        "cssVar": "--accent-secondary-hover",
        "value": {
            "light": "var(--purple-700)",
            "dark": "var(--purple-700)"
        }
    },
    "accent-teal": {
        "key": "accent-teal",
        "label": "Accent Teal",
        "cssVar": "--accent-teal",
        "value": {
            "light": "var(--teal-500)",
            "dark": "var(--teal-500)"
        }
    },
    "accent-teal-hover": {
        "key": "accent-teal-hover",
        "label": "Accent Teal Hover",
        "cssVar": "--accent-teal-hover",
        "value": {
            "light": "var(--teal-700)",
            "dark": "var(--teal-700)"
        }
    },
    "accent-success": {
        "key": "accent-success",
        "label": "Accent Success",
        "cssVar": "--accent-success",
        "value": {
            "light": "var(--green-500)",
            "dark": "var(--green-500)"
        }
    },
    "accent-warning": {
        "key": "accent-warning",
        "label": "Accent Warning",
        "cssVar": "--accent-warning",
        "value": {
            "light": "var(--yellow-500)",
            "dark": "var(--yellow-500)"
        }
    },
    "accent-danger": {
        "key": "accent-danger",
        "label": "Accent Danger",
        "cssVar": "--accent-danger",
        "value": {
            "light": "var(--red-500)",
            "dark": "var(--red-500)"
        }
    },
    "accent-info": {
        "key": "accent-info",
        "label": "Accent Info",
        "cssVar": "--accent-info",
        "value": {
            "light": "var(--cyan-500)",
            "dark": "var(--cyan-500)"
        }
    },
    "on-accent-primary": {
        "key": "on-accent-primary",
        "label": "On Accent Primary",
        "cssVar": "--on-accent-primary",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "on-accent-secondary": {
        "key": "on-accent-secondary",
        "label": "On Accent Secondary",
        "cssVar": "--on-accent-secondary",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "on-accent-teal": {
        "key": "on-accent-teal",
        "label": "On Accent Teal",
        "cssVar": "--on-accent-teal",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "on-accent-success": {
        "key": "on-accent-success",
        "label": "On Accent Success",
        "cssVar": "--on-accent-success",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "on-accent-warning": {
        "key": "on-accent-warning",
        "label": "On Accent Warning",
        "cssVar": "--on-accent-warning",
        "value": {
            "light": "#1f2933",
            "dark": "#0b0f19"
        }
    },
    "on-accent-danger": {
        "key": "on-accent-danger",
        "label": "On Accent Danger",
        "cssVar": "--on-accent-danger",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    },
    "on-accent-info": {
        "key": "on-accent-info",
        "label": "On Accent Info",
        "cssVar": "--on-accent-info",
        "value": {
            "light": "#ffffff",
            "dark": "#0b0f19"
        }
    }
} as const;
